config/routes.rb
Rails.application.routes.draw do
  get 'profiles/index'
  get 'villages/index'
  get 'sign_up/profile'
  resources :courses
 

  devise_for :users , controllers: { sessions: 'users/sessions',  omniauth_callbacks: 'users/omniauth_callbacks' }
 
devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
end

    
  
  resources :employers 
  resources :jobs
  resources :profiles
  resources :courses
  resources :villages
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "jobs#index"

end 

app/models/village.rb
class Village < ApplicationRecord
end

app/controllers/villages_controller.rb
class VillagesController < ApplicationController
  def index
     
     @villages= Village.all
     
  end

def new 

  @village =Village.new
   end 

   def create

    @village = Village.new(village_params)
      
      if @village.save
        redirect_to @village

     else   
      
      render :new, unprocessable_entity

    end
end 

def show
  @village =Village.find(params[:id])
end 
     
  private
    def village_params
      params.require(:village).permit(:village_name, :village_block, :pin_code,:post_office,:district)
    end

end 

app/helpers/villages_helper.rb
module VillagesHelper
end

app/views/villages/index.html.erb
<h1>Village_detail</h1>



<table>
	 
	 <tr>
	 	<th> ID </th>
	 	<th> Villlage_Name </th>
	 	<th> Villages_BLock </th>
	 	<th> Pin_Code   </th>
	 	<th> Post_Office </th>
	 	<th> District </th>
	 	<th> link</th>

	 </tr>

 <% @villages.each do|village| %>
    
    <tr>
    	<td><%=village.id%></td>
    	<th><%=village.village_name%></th>
    	<th><%=village.village_block%></th>
    	<th><%=village.pin_code%></th>
    	<th><%=village.post_office %></th>
    	<th><%=village.district%></th>
        <th><%=link_to "show", village_path(village.id)%></th>
    </tr>

    <% end %>

   </table>

    <%= link_to "new_village", new_village_path %>

app/views/villages/new.html.erb
<%= form_with(model: @village) do |form| %> 




 <div>
    <%= form.label :Village_Name , style: "display: block" %>
    <%= form.text_field :village_name  %>
  </div>	

  <div>
  	<%= form.label :Village_Block, style: "display: block" %>
     <%= form.text_field :village_block %>
  </div>

  <div>
  	<%= form.label :Pin_Code, style: "display: block" %>
  	<%= form.text_field :pin_code %>

  </div>

  <div>
  	<%=form.label :Post_Office, style: "display: block"%>
  	<%=form.text_field :post_office %>

  </div>

  <div>
  	
  	<%=form.label :District, style: "display: block"%>
  	<%=form.text_field :district %>
  </div>


  <div>
       <%=form.submit %>
  </div>

  <%end %>

app/views/villages/show.html.erb
<h1>Village_Detail</h1>


<p>
    <strong> ID: </strong>
    <%= @village.id %>
<p>

  <p>
    <strong>Village_Block:</strong>
    <%= @village.village_name %>
    <p>

 <p>
    <strong>Village_BLock: </strong>
    <%= @village.village_block %>
  <p>

  <p>
    <strong>Pin_Code:</strong>
    <%=@village.pin_code %>

  </p>

  <p>
    <strong> Post_Office: </strong>
     <%=@village.post_office %>

  </p>

  <p>
    <strong> District: </strong>
    <%=@village.district %>

  </p> 





<div>
  <%= link_to "Edit this village", edit_village_path(@village) %> |
  <%= link_to "Back to villages", villages_path %>

  <%= button_to "Destroy this village", @village, method: :delete %>
</div>