config/routes.rb
Rails.application.routes.draw do
  get 'profiles/index'
  get 'villages/index'
  get 'sign_up/profile'
  resources :courses
 

  devise_for :users , controllers: { sessions: 'users/sessions',  omniauth_callbacks: 'users/omniauth_callbacks' }
 
devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
end

    
  
  resources :employers 
  resources :jobs
  resources :profiles
  resources :courses
  resources :villages
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "jobs#index"

end 

app/models/employer.rb
class Employer < ApplicationRecord
  has_many :jobs 
end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
  before_action :set_employer, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, :only => [:new, :edit,:destroy]
  # GET /employers or /employers.json
  def index
    @employers = Employer.all
  end

  # GET /employers/1 or /employers/1.json
  def show
  end

  # GET /employers/new
  def new
    @employer = Employer.new
  end

  # GET /employers/1/edit
  def edit    
  end

  # POST /employers or /employers.json
  def create
    @employer = Employer.new(employer_params)

    respond_to do |format|
      if @employer.save
        format.html { redirect_to employer_url(@employer), notice: "Employer was successfully created." }
        format.json { render :show, status: :created, location: @employer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employers/1 or /employers/1.json
  def update
    respond_to do |format|
      if @employer.update(employer_params)
        format.html { redirect_to employer_url(@employer), notice: "Employer was successfully updated." }
        format.json { render :show, status: :ok, location: @employer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employers/1 or /employers/1.json
  def destroy
    @employer.destroy

    respond_to do |format|
      format.html { redirect_to employers_url, notice: "Employer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employer
      @employer = Employer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employer_params
      params.require(:employer).permit(:name, :email, :company_name, :contact, :social_url)
    end
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/views/employers/_employer.html.erb
<div id="<%= dom_id employer %>">
  <p>
    <strong>Name:</strong>
    <%= employer.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= employer.email %>
  </p>

  <p>
    <strong>Company name:</strong>
    <%= employer.company_name %>
  </p>

  <p>
    <strong>Contact:</strong>
    <%= employer.contact %>
  </p>

  <p>
    <strong>Social url:</strong>
    <%= employer.social_url %>
  </p>

</div>

app/views/employers/_form.html.erb
<%= form_with(model: employer) do |form| %>
  <% if employer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(employer.errors.count, "error") %> prohibited this employer from being saved:</h2>

      <ul>
        <% employer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :company_name, style: "display: block" %>
    <%= form.text_field :company_name %>
  </div>

  <div>
    <%= form.label :contact, style: "display: block" %>
    <%= form.text_field :contact %>
  </div>

  <div>
    <%= form.label :social_url, style: "display: block" %>
    <%= form.text_field :social_url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/employers/edit.html.erb
<h1>Editing employer</h1>

<%= render "form", employer: @employer %>

<br>

<div>
  <%= link_to "Show this employer", @employer %> |
  <%= link_to "Back to employers", employers_path %>
</div>

app/views/employers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Employers</h1>

<div id="employers">
  <% @employers.each do |employer| %>
    <%= render employer %>
    <p>
      <%= link_to "Show this employer", employer %>
    </p>
  <% end %>
</div>

<%= link_to "New employer", new_employer_path %>

app/views/employers/new.html.erb
<h1>New employer</h1>

<%= render "form", employer: @employer %>

<br>

<div>
  <%= link_to "Back to employers", employers_path %>
</div>

app/views/employers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @employer %>

<div>
  <%= link_to "Edit this employer", edit_employer_path(@employer) %> |
  <%= link_to "Back to employers", employers_path %>

  <%= button_to "Destroy this employer", @employer, method: :delete %>

 
</div>