config/routes.rb
Rails.application.routes.draw do
  get 'profiles/index'
  get 'villages/index'
  get 'sign_up/profile'
  resources :courses
 

  devise_for :users , controllers: { sessions: 'users/sessions',  omniauth_callbacks: 'users/omniauth_callbacks' }
 
devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
end

    
  
  resources :employers 
  resources :jobs
  resources :profiles
  resources :courses
  resources :villages
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "jobs#index"

end 

app/views/layouts/_nav.html.erb
<% if current_user.present? %>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid p-2">
    <a class="navbar-brand" href="#">
      <img src="/docs/5.0/assets/brand/bootstrap-logo.svg" alt="" width="30" height="24" class="d-inline-block align-text-top">
      <%= link_to "jobs",jobs_path , class: ' text-success nav-link' %>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="  
            navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item ">
          <%= link_to "employers", employers_path , class: ' text-success nav-link' %>
        </li>

        <li class="nav-item">
          <%= link_to "courses", courses_path, class: ' text-success nav-link' %>
        </li>

        <li class="nav-item">
          <%= link_to "villages",villages_path , class: ' text-success nav-link' %>
        </li>
      </ul>

      <form class="d-flex">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class=" nav-item">
            <%= link_to "logout", destroy_user_session_path  , :method => :delete, class: ' text-success nav-link'%>
          </li>
        </ul>

        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

<% else %> 

<nav class="navbar navbar-expand-lg navbar-light bg-light ">
  <div class="container-fluid p-2">
    <a class="navbar-brand" href="#">
      <img src="/docs/5.0/assets/brand/bootstrap-logo.svg" alt="" width="30" height="24" class="d-inline-block align-text-top">
      <%= link_to "jobs",jobs_path , class: ' text-success nav-link' %>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="
            navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">       
      </ul>
      <form class="d-flex">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class=" text-success nav-link" href="#">Contact_us</a>
          </li>

          <li class="nav-item">
          <%= link_to "Sign_In",  user_session_path  , class: ' text-success nav-link'%>
          </li>

          <li class="nav-item">
           <%= link_to "Sign_Up", new_user_registration_path  , class: '    btn text-success btn-outline-dark' %>
          </li>

        </ul>        
      </form>
    </div>
  </div>
</nav>
<% end %>



 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jobs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     
     
    

    <%= stylesheet_pack_tag "application", media: 'all', "data-turbo-track": "reload" %>
    <%= javascript_pack_tag "application" %>
  </head>

  <body>
 <%= render 'layouts/nav' %>


 <div class="container">
 
    <%= yield %>
  </div>

  </body>
</html>